"""remove avtar_url to user model

Revision ID: e4b04fdc815a
Revises: 35f5520e3ece
Create Date: 2020-03-04 07:42:07.342881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4b04fdc815a'
down_revision = '35f5520e3ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', mysql.VARCHAR(length=80), nullable=True))
    # ### end Alembic commands ###
